version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    restart: unless-stopped

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/app 
    working_dir: /app
    command: composer install
    depends_on:
      - app